### ISSUE TITLE
"params" argument cannot be specified in the package.json

### ISSUE THREAD

**Issue by kptdobe** [adobe/openwhisk-action-builder#105]
Try: 
```
"wsk": {
    "name": "...,
    "params": {
      "p1": "vp1"
    }
  }
```

The p1 params is not available in the action.

From the documentation, https://github.com/adobe/openwhisk-action-builder#specifying-arguments-in-the-packagejson I expect this should be doable.
Ask here is to either change the doc to specify which arguments are supported in the `package.json` or implement the support for the params argument.

cc @tripodsan @dominique-pfister

**Comment by tripodsan** [comment]
I think this is a limitation of yargs. the following should work.

```
"wsk": {
    "name": "...,
    "params": [
      "p1=vp1"
    ]
  }
```

**Comment by tripodsan** [comment]
just tested, and it works as expected:

```
  "wsk": {
    "name": "toby-test-fetch",
    "params": {
      "LOG_LEVEL": "debug",
      "MY_TEST": "Hello, world."
    }
```

```
$ wsk action get toby-test-fetch | tail -n+2 | jq .parameters
[
  {
    "key": "LOG_LEVEL",
    "value": "debug"
  },
  {
    "key": "MY_TEST",
    "value": "Hello, world."
  }
]
```
