### ISSUE TITLE
Clarify how to change the log level

### ISSUE THREAD

**Issue by kptdobe** [adobe/openwhisk-action-builder#106]
I could not find a fully satisfying way to define the log level of my action built via the builder.

I tried multiple solutions provided by @tripodsan, like `params: [ "LOG_LEVEL=debug"]`, `params: [ "CORALOGIX_LOG_LEVEL=debug"]` (in `package.json`) but none worked.

Only solution that seemed to work was:

```
"wsk": {
    "name": ...,
    "linksPackage": "helix-services",
    "params-file": [
      ".env"
    ]
  }
```
where `.env` contains `CORALOGIX_LOG_LEVEL=debug`.

Multiple things to clarify:
- why `CORALOGIX_LOG_LEVEL` ? I do not use Coralogix in my setup, I would expect something like `LOG_LEVEL`
- how to pass the param ? This is certainly related to #105 

This could be fixed (if needed) and documented.

**Comment by kptdobe** [comment]
Also, to make sure we are talking about the same thing, I use the logger from the params:

```
async function main(params = {}) {
  const {
    __ow_logger: log,
  } = params;
 log.debug('Hello World');
}
```

**Comment by kptdobe** [comment]
Note that there is a delay for the logs to be retrieved after the activation: running `wsk activation logs xyz` might return nothing if called to early!

**Comment by kptdobe** [comment]
While trying to define a rule for log levels, I came up with https://github.com/adobe/openwhisk-action-utils/issues/63.

**Comment by tripodsan** [comment]
https://github.com/adobe/openwhisk-action-logger/issues/32

use `wsk-builder deploy -p LOG_LEVEL=debug` or specify in the package.json

```
  "wsk": {
    "name": "...",
    "params": {
      "LOG_LEVEL": "debug",
    }
```

**Comment by kptdobe** [comment]
I tested (again) your proposal and it still does not work for me. I created this repo so maybe you see what I doing wrong: https://github.com/kptdobe/helix-dummy (from helix-service template).

I run: 
```
$ npm install
$ npm run deploy
$ curl -v https://adobeioruntime.net/api/v1/web/acapt/helix-services-private/helix-dummy@1.4.9
$  wsk activation logs --last
```

and I get:

```
$ wsk activation logs --last                                              
2020-01-31T07:51:15.125Z       stderr: [ERROR] log.error
2020-01-31T07:51:15.125Z       stderr: [WARN] log.warn
2020-01-31T07:51:15.125Z       stderr: log.info
```

No debug log while param is set as you describe: https://github.com/kptdobe/helix-dummy/blob/master/package.json#L23-L25
I might be doing something wrong because when I change the `LOG_LEVEL` to `trace`, I do not have any log at all...

**Comment by kptdobe** [comment]
Now, whatever I do, I have no log anymore...

**Comment by kptdobe** [comment]
Another finding: if I put the `log.trace` first, I have no log at all... see branch https://github.com/kptdobe/helix-dummy/tree/trace-first

**Comment by kptdobe** [comment]
@tripodsan can you reproduce the same behaviour ?

**Comment by kptdobe** [comment]
OK... I found it
https://github.com/adobe/helix-service/commit/c939bb98fe48de0f99fff8000a95194b9555cd23

Until 7h ago, the `helix-service` template was using an old version of `@adobe/openwhisk-action-logger`... Upgrading to latest version fix all my issues...

How to lose 2 days...
