### ISSUE TITLE
Loading static files with __dirname and path.resolve fails

### ISSUE THREAD

**Issue by trieloff** [adobe/openwhisk-action-builder#39]
See https://github.com/adobe/helix-publish/issues/118

This might be a fix, but I'm not sure about the side effects: https://codeburst.io/use-webpack-with-dirname-correctly-4cad3b265a92

**Comment by trieloff** [comment]
See https://github.com/adobe/helix-publish/pull/119/files for the workaround I had to apply

**Comment by tripodsan** [comment]
I think the problem is that the path calculated in:
```
  const vclfile = path.resolve(__dirname, '../../layouts/fastly/helix.vcl');
```
becomes wrong, after the javascript is bundled
