### ISSUE TITLE
Pluggable Wrappers/Middleware

### ISSUE THREAD

**Issue by trieloff** [adobe/openwhisk-action-builder#59]
It seems like the creation of wrappers that work like express middleware and decorate the `main` function is a common pattern for our OpenWhisk actions. The list of wrappers we use on a regular basis so far include
- `adobe/helix-pingdom-status`
- `epsagon/epsagon-node`
- `openwhisk-loggly-wrapper`
and we can expect more to come. In order to unify and simplify the creation of these wrappers, it would be great to move from a model where you have to add them explicitly to your `index.js` to a model where you can specify wrap wrappers to apply on the `wsk-builder` command line.

Each wrapper would pick up configuration from the `package.json` and added as part of the finished output file. This would also enable the creation of smaller, more single-purpose wrappers such as:

- one that turns ALL_CAPS_PARAMS into environment vars
- one that removes and hides ALL_CAPS_PARAMS

**Comment by tripodsan** [comment]
I don't think this is so great because the code becomes intransparent for the developer and it will be hard to get the right mix of configurability of the wrappers.

**Comment by trieloff** [comment]
Agree. Closing.
