### ISSUE TITLE
Shouldn't OW settings in secrets.env take precendence over .wskprops?

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/openwhisk-action-builder#98]
In:

https://github.com/adobe/openwhisk-action-builder/blob/66ce67b1fd049d043f486558ec2d1d812c60f2fa/src/DevelopmentServer.js#L80

entries in an eventual `.wskprops` file (e.g. AUTH) take precedence over parameters defined in `secrets/secrets.env` (e.g. WSK_AUTH) of a project. 

It took me some time to figure out, why the `onedrive-listener` suddenly stopped working - entries in our `secrets.env` were being overwritten by my personal namespace settings in `.wskprops` -  so I'm wondering whether this shouldn't be the other way round? Or should we generally avoid putting WSK_xxx settings in `secrets.env`?

**Comment by tripodsan** [comment]
the secrets.env (aka the params) are not intended to pass `WSK_AUTH`, since this is a deploy time value. so I would even remove the `params.WSK_AUTH` fallback.
